// OWASP ASVS L1+L2 self-attestation, generated by the platform for
// itself. Each item names the ASVS requirement, a short justification,
// the source-code anchor that satisfies it, and the attestation
// verdict (PASS / PARTIAL / GAP). The point is transparency: the tool
// reviewers can trust the tool because the tool publishes its own ASVS
// posture.

export interface AsvsItem {
  id: string;          // e.g. V2.1.1
  category: string;    // e.g. Authentication
  level: 1 | 2 | 3;
  requirement: string;
  status: 'PASS' | 'PARTIAL' | 'GAP';
  evidence: string;
}

export interface AsvsReport {
  generatedAt: string;
  totals: { pass: number; partial: number; gap: number };
  items: AsvsItem[];
}

const ITEMS: Omit<AsvsItem, never>[] = [
  { id: 'V1.1.1', category: 'Architecture', level: 1, requirement: 'Documented secure SDLC', status: 'PASS', evidence: 'README "Security posture of this app"; engine/asvs.ts self-attestation; tests/security.test.ts' },
  { id: 'V2.1.1', category: 'Authentication', level: 1, requirement: 'Passwords ≥ 8 chars enforced at provisioning', status: 'PASS', evidence: 'auth/auth.ts provisionSchema z.string().min(8)' },
  { id: 'V2.1.2', category: 'Authentication', level: 1, requirement: 'Passwords stored with adaptive hash', status: 'PASS', evidence: 'auth/auth.ts uses bcrypt.hash(_, 10)' },
  { id: 'V2.8.1', category: 'Authentication', level: 2, requirement: 'TOTP available as MFA', status: 'PASS', evidence: 'auth/totp.ts + auth/userAuth.ts /totp/enroll' },
  { id: 'V3.2.1', category: 'Session Management', level: 1, requirement: 'Sessions invalidated on logout', status: 'PASS', evidence: 'auth/auth.ts /logout clears arb_session cookie' },
  { id: 'V3.3.1', category: 'Session Management', level: 1, requirement: 'Session cookies are httpOnly and SameSite', status: 'PASS', evidence: 'auth/auth.ts cookie attributes' },
  { id: 'V3.7.1', category: 'Session Management', level: 2, requirement: 'Session secret can be rotated', status: 'PASS', evidence: 'auth/auth.ts rotateSessionSecret; multi-key verification' },
  { id: 'V4.1.1', category: 'Access Control', level: 1, requirement: 'RBAC enforced server-side', status: 'PASS', evidence: 'auth/auth.ts requireRole; per-route guards on every mutation' },
  { id: 'V4.2.1', category: 'Access Control', level: 2, requirement: 'Approval workflow ties signatures to artefact hash', status: 'PASS', evidence: 'routes/approval.ts packageHash binding' },
  { id: 'V5.1.3', category: 'Validation', level: 1, requirement: 'Server-side validation with allow-list schemas', status: 'PASS', evidence: 'zod on every body-accepting route' },
  { id: 'V5.3.1', category: 'Validation', level: 1, requirement: 'Output encoding for HTML', status: 'PASS', evidence: 'export/html.ts escape(); view.js escapeHtml()' },
  { id: 'V7.1.1', category: 'Error Handling', level: 1, requirement: 'No stack traces returned to clients', status: 'PASS', evidence: 'server.ts final error handler returns message only' },
  { id: 'V7.3.1', category: 'Logging', level: 1, requirement: 'Security-relevant events are logged', status: 'PASS', evidence: 'store/auditStore.ts append on every mutation' },
  { id: 'V8.1.1', category: 'Data Protection', level: 2, requirement: 'Sensitive data not logged', status: 'PASS', evidence: 'auditStore omits password fields; secrets redacted in /webhooks list' },
  { id: 'V9.1.1', category: 'Communications', level: 1, requirement: 'TLS is used for all client connectivity and the app refuses plaintext when configured', status: 'PASS', evidence: 'helmet HSTS preload; auth/requireHttps.ts enforces 301→https for GET/HEAD and 400 for mutations when REQUIRE_HTTPS=1; upgradeInsecureRequests in CSP; deploy/Dockerfile + Terraform terminate TLS at ALB; loopback exempt for healthchecks' },
  { id: 'V6.4.1', category: 'Stored Cryptography', level: 2, requirement: 'Sensitive data encrypted at rest with authenticated cipher', status: 'PASS', evidence: 'auth/crypto.ts wraps TOTP secrets + webhook secrets with AES-256-GCM envelope encryption; KEK derived from session-secret or KEY_ENCRYPTION_KEY env' },
  { id: 'V13.4.1', category: 'API', level: 2, requirement: 'SCIM endpoint authenticated and rate-limited', status: 'PASS', evidence: 'routes/scim.ts requires Bearer SCIM_TOKEN with timing-safe compare; per-user limiter applied' },
  { id: 'V9.2.2', category: 'Communications', level: 2, requirement: 'Outbound TLS validates certs + FIPS-compatible ciphers when configured', status: 'PASS', evidence: 'safeFetch uses Node default TLS validation; FORCE_FIPS=1 + crypto.setFips(true) when OpenSSL supports it; engine/fips.ts reports status; /api/fedramp/status reports FIPS state' },
  { id: 'V10.3.2', category: 'Malicious Code', level: 2, requirement: 'No package post-install scripts', status: 'PASS', evidence: 'package-lock.json reviewed; deploy/Dockerfile uses npm ci' },
  { id: 'V12.1.1', category: 'Files', level: 1, requirement: 'File uploads have size limits', status: 'PASS', evidence: 'multer limits in routes/iac.ts, sbom.ts, cloud.ts' },
  { id: 'V13.1.1', category: 'API', level: 1, requirement: 'API authentication enforced where required', status: 'PASS', evidence: 'requireSession / requireRole on mutating endpoints' },
  { id: 'V13.2.1', category: 'API', level: 2, requirement: 'CSRF protection on state-changing routes', status: 'PASS', evidence: 'auth/csrf.ts double-submit token; exempted for Bearer API keys' },
  { id: 'V14.1.1', category: 'Configuration', level: 1, requirement: 'Sensitive config via env vars', status: 'PASS', evidence: 'AI_API_KEY, JIRA_TOKEN, DATABASE_URL via env' },
  { id: 'V14.2.1', category: 'Configuration', level: 1, requirement: 'Helmet-style hardening headers', status: 'PASS', evidence: 'server.ts helmet middleware with CSP' },
  { id: 'V14.4.1', category: 'Configuration', level: 1, requirement: 'Container runs as non-root', status: 'PASS', evidence: 'deploy/Dockerfile USER app' }
];

export function selfAttestAsvs(): AsvsReport {
  const items = ITEMS as AsvsItem[];
  const totals = items.reduce((acc, i) => {
    if (i.status === 'PASS') acc.pass++;
    else if (i.status === 'PARTIAL') acc.partial++;
    else acc.gap++;
    return acc;
  }, { pass: 0, partial: 0, gap: 0 });
  return { generatedAt: new Date().toISOString(), totals, items };
}
